import { useEffect, useState } from "react";
import { api } from "../services/api";
import { useAuth } from "../context/AuthContext";

const emptyProduct={name:"",description:"",price:"",image:"",category:"Chicken",weight:500,stock:0,isAvailable:true};

export default function Admin({navigate}) {
  const {user,logout}=useAuth(); const [tab,setTab]=useState("dashboard"); const [dash,setDash]=useState(null); const [products,setProducts]=useState([]); const [orders,setOrders]=useState([]); const [form,setForm]=useState(emptyProduct); const [phone,setPhone]=useState(""); const [customer,setCustomer]=useState(null); const [cart,setCart]=useState([]); const [message,setMessage]=useState("");
  const load=async()=>{try{const [d,p,o]=await Promise.all([api("/dashboard/today"),api("/products/inventory"),api("/orders")]);setDash(d.dashboard);setProducts(p.inventory||[]);setOrders(o.orders||[]);}catch(e){setMessage(e.message);}};
  useEffect(()=>{if(user?.role!=="admin"){navigate("/login");return;}load();},[]);
  const create=async()=>{try{await api("/products",{method:"POST",body:JSON.stringify({...form,price:Number(form.price),weight:Number(form.weight),stock:Number(form.stock)})});setForm(emptyProduct);setMessage("Product created.");load();}catch(e){setMessage(e.message);}};
  const status=async(id,next)=>{try{await api(`/orders/${id}/status`,{method:"PATCH",body:JSON.stringify({status:next})});load();}catch(e){setMessage(e.message);}};
  const lookup=async()=>{try{const d=await api(`/users/customer?phone=${encodeURIComponent(phone)}`);setCustomer(d.customer);setMessage("Customer found.");}catch(e){setCustomer(null);setMessage(e.message);}};
  const posAdd=(p)=>setCart(c=>{const x=c.find(i=>i.product===p._id);return x?c.map(i=>i.product===p._id?{...i,quantity:i.quantity+1}:i):[...c,{product:p._id,quantity:1,price:p.price,name:p.name}];});
  const posCreate=async()=>{if(!customer||!cart.length)return setMessage("Select customer and products.");try{const d=await api("/orders/pos",{method:"POST",body:JSON.stringify({customerId:customer._id,items:cart.map(i=>({product:i.product,quantity:i.quantity})),paymentMethod:"COD"})});setMessage(`POS order created: ${d.order?._id?.slice(-8)}`);setCart([]);load();}catch(e){setMessage(e.message);}};
  if(user?.role!=="admin")return null;
  return <div className="mx-auto max-w-7xl px-5 py-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold tracking-[.18em] text-[#c62828]">ADMIN</p><h1 className="text-3xl font-black">Dilli Cuts Control</h1></div><button onClick={()=>{logout();navigate("/");}} className="rounded-full border px-5 py-2.5 text-sm font-bold">Logout</button></div>
    <div className="mt-7 flex gap-2 overflow-x-auto">{["dashboard","products","orders","pos"].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-5 py-2.5 text-sm font-bold ${tab===x?"bg-[#171717] text-white":"bg-white"}`}>{x}</button>)}</div>
    {message&&<div className="mt-4 rounded-2xl bg-black/5 p-3 text-sm">{message}</div>}
    {tab==="dashboard"&&dash&&<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Today orders",dash.todayOrders],["Today sales",`₹${dash.todaySales}`],["Pending",dash.pendingOrders],["Customers",dash.totalCustomers],["New today",dash.newCustomersToday],["Low stock",dash.lowStockProducts],["Negative stock",dash.negativeStockProducts],["Online / POS",`${dash.onlineOrders} / ${dash.posOrders}`]].map(([a,b])=><div key={a} className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-sm text-black/50">{a}</p><b className="mt-2 block text-2xl">{b}</b></div>)}</div>}
    {tab==="products"&&<div className="mt-7 grid gap-6 lg:grid-cols-[360px_1fr]"><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Add product</h2>{Object.keys(emptyProduct).filter(k=>k!=="isAvailable").map(k=><input key={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k} className="mt-3 w-full rounded-2xl border px-4 py-3"/>)}<button onClick={create} className="mt-4 w-full rounded-2xl bg-[#c62828] py-3 font-bold text-white">Create</button></section><section className="space-y-3">{products.map(p=><div key={p._id} className="flex items-center gap-4 rounded-3xl bg-white p-4 shadow-sm"><div className="h-16 w-16 overflow-hidden rounded-2xl bg-black/5">{p.image&&<img src={p.image} className="h-full w-full object-cover"/>}</div><div className="flex-1"><b>{p.name}</b><p className="text-xs text-black/50">₹{p.price} · {p.weight}g</p></div><span className={`text-sm font-bold ${p.stock<0?"text-red-600":""}`}>Stock {p.stock}</span></div>)}</section></div>}
    {tab==="orders"&&<div className="mt-7 space-y-3">{orders.map(o=><div key={o._id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><b>#{o._id.slice(-8).toUpperCase()} · {o.user?.name||"Customer"}</b><p className="text-sm text-black/50">{o.user?.phone}</p></div><b>₹{o.totalAmount}</b></div><div className="mt-4 flex flex-wrap gap-2">{["ACCEPTED","PROCESSING","PACKED","OUT_FOR_DELIVERY","DELIVERED","CANCELLED"].map(s=><button disabled={o.status===s||o.status==="DELIVERED"||o.status==="CANCELLED"} key={s} onClick={()=>status(o._id,s)} className="rounded-full border px-3 py-1.5 text-xs font-bold disabled:opacity-30">{s}</button>)}</div></div>)}</div>}
    {tab==="pos"&&<div className="mt-7 grid gap-6 lg:grid-cols-[360px_1fr]"><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Walk-in customer</h2><div className="mt-4 flex gap-2"><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone" className="min-w-0 flex-1 rounded-2xl border px-4 py-3"/><button onClick={lookup} className="rounded-2xl bg-[#171717] px-4 font-bold text-white">Find</button></div>{customer&&<div className="mt-4 rounded-2xl bg-black/5 p-4"><b>{customer.name}</b><p className="text-sm">{customer.phone}</p></div>}<div className="mt-6 border-t pt-5"><b>Bill</b>{cart.map(i=><div key={i.product} className="mt-2 flex justify-between text-sm"><span>{i.name} × {i.quantity}</span><span>₹{i.price*i.quantity}</span></div>)}<button onClick={posCreate} className="mt-5 w-full rounded-2xl bg-[#c62828] py-3 font-bold text-white">Create COD bill</button></div></section><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{products.filter(p=>p.isAvailable).map(p=><button key={p._id} onClick={()=>posAdd(p)} className="rounded-3xl bg-white p-5 text-left shadow-sm hover:shadow-lg"><b>{p.name}</b><p className="mt-1 text-sm text-black/50">₹{p.price}</p><span className="mt-4 inline-block rounded-full bg-black px-4 py-2 text-xs font-bold text-white">+ Add</span></button>)}</section></div>}
  </div>;
}
